site_name: Vulcain
dev_addr: 0.0.0.0:8000
theme: mkdocs
pages:
  - Home: index.md
  - Documentation:
    - Overview: 'reference/index.md'
    - Actions: 'reference/actions.md'
    - Queries: 'reference/query.md'
    - Events: 'reference/event.md'  
    - 'Domain models': 'reference/domain.md'  
    - "Dependencies injection" : 'reference/injection.md'
    - Commands: 'reference/commands.md'
    - Configurations: 'reference/configurations.md'
    - Monitoring: 'reference/metrics.md'
    - Security: 'reference/security.md'
  - About: 
    - license: 'about/license.md'