site_name: Vulcain
dev_addr: 0.0.0.0:8000
theme: 
  name: 'material'
  custom_dir: theme
site_url: https://vulcainjs.github.io
repo_url: https://github.com/vulcainjs/vulcainjs.github.io
edit_uri: edit/mkdocs/docs/
site_author: Alain Metge
copyright: Copyright © 2017 Zenasoft
#google_analytics: ['UA-49523450-2', 'auto']
pages:
  - Home: index.md
  - "Getting started": gettingStarted/index.md
  #- Documentation:
  #  - Overview: 'reference/index.md'
  #  - Actions: 'reference/actions.md'
  #  - Queries: 'reference/query.md'
  #  - Events: 'reference/event.md'  
  #  - 'Domain models': 'reference/domain.md'  
  #  - "Dependencies injection" : 'reference/injection.md'
  #  - Commands: 'reference/commands.md'
  #  - Configurations: 'reference/configurations.md'
  #  - Monitoring: 'reference/metrics.md'
  #  - Security: 'reference/security.md'
  #  - Testing: 'reference/testing.md'
  #- Articles:
  #  - "How to index": 'articles/index.md'
  #  - "Users service": 'articles/users.md'
  #  - "Configuration properties server": 'articles/dynamicProperties.md'
  #  - "Setup Vulcain Demo on Azure": 'articles/setupVulcainDemo.md'
  #- "Plugins" : 'plugins/index.md'
  - About: 
    - license: 'about/license.md'
extra:
  disqus: 'vulcainjs'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  social:
    - type: 'github'
      link: 'https://github.com/vulcainjs'
  palette:
    primary: 'blue'
    accent: 'light blue'
markdown_extensions:
  - toc(permalink=true)
  - admonition
  - codehilite(guess_lang=false)
  - footnotes