site_name: Vulcain
dev_addr: 0.0.0.0:8000
theme_dir: 'docs/theme'
theme: 'material'
site_url: https://vulcainjs.github.io
repo_url: https://github.com/vulcainjs/vulcainjs.github.io
site_author: Alain Metge
copyright: Copyright © 2017 Zenasoft
pages:
  - Home: index.md
  - "Getting started":
    - "Run sample": gettingStarted/index.md
  - Documentation:
    - Overview: 'reference/index.md'
    - Actions: 'reference/actions.md'
    - Queries: 'reference/query.md'
    - Events: 'reference/event.md'  
    - 'Domain models': 'reference/domain.md'  
    - "Dependencies injection" : 'reference/injection.md'
    - Commands: 'reference/commands.md'
    - Configurations: 'reference/configurations.md'
    - Monitoring: 'reference/metrics.md'
    - Security: 'reference/security.md'
  - About: 
    - license: 'about/license.md'
extra:
  palette:
    primary: 'blue'
    accent: 'light blue'
markdown_extensions:
  - toc
  - admonition
  - codehilite(guess_lang=false)
  - toc(permalink=true)
  - footnotes
